---
name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,ome
          environment-file: environment.yml
          python-version: 3.9

      - name: Run pytest
        shell: bash -l {0}
        run: pytest -vxk "not omero"
